FROM node:20-alpine

WORKDIR /home/solid/apps/server

COPY package.json .
COPY --from=monorepo package.json package-lock.json /home/solid/
COPY --from=monorepo apps/ /home/solid/apps/
# COPY --from=monorepo packages/ /home/solid/packages/

RUN npm ci

EXPOSE 3000

ENTRYPOINT ["npm", "run", "dev"]