FROM oven/bun:1-alpine

WORKDIR /home/solid/apps/server

COPY package.json .
COPY --from=monorepo package.json bun.lockb /home/solid/
COPY --from=monorepo apps/ /home/solid/apps/
COPY --from=monorepo packages/ /home/solid/packages/

RUN bun install

EXPOSE 3000

ENTRYPOINT ["bun", "run", "dev"]